title: [FOSDEM 2026 Open Hardware and CAD/CAM Devroom]
description: [1 February 2026 â€” Brussels, Belgium]
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown
highlighter: rouge
