title: FOSDEM 2026 Open Hardware and CAD/CAM Devroom
description: Home of the Open Hardware and CAD/CAM Devroom at FOSDEM 2026, 1 February 2026 in Brussels, Belgium
theme: jekyll-theme-slate

markdown: kramdown
highlighter: rouge
